# Generated by Django 6.0.4 on 2026-04-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
