# Generated by Django 6.0.4 on 2026-04-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrderApp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
